//Assignment on variable Decleration
var myFullName;
myFullName="Swapnil  Aade";
console.log("01. initial value-", myFullName);
var myFullName="Swapnil Ramesh Aade";
console.log("02. updated value-", myFullName);
console.log("=============================");
var myLove="i love only js";
console.log("myLove");
var fname="Swapnil";
console.log("first name-", fname);
var lname="Aade";
console.log("last name-", lname);
var age="21";
console.log("age-", age);
var address="Pune";
console.log("address-", address);
var pin-code="412207";
console.log(pin - code -), pin - code;
var gender="Male";
console.log("gender-", gender);
var is_married="Yes";
console.log("is_married-", is_married); 
